apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-custom-mm2
spec:
  # Aggiornato alla versione Kafka 3.9.0
  version: 3.9.0
  replicas: 1
  
  # Definisci la connessione al cluster di destinazione dove MM2 verrà eseguito
  connectCluster: "my-target-cluster" 
  
  # Definisci gli alias per i cluster Kafka di origine e destinazione
  clusters:
  - alias: "my-source-cluster"
    bootstrapServers: my-source-cluster-kafka-bootstrap:9092
  - alias: "my-target-cluster"
    bootstrapServers: my-target-cluster-kafka-bootstrap:9092
  
  # --- Configurazione dell'Immagine Custom ---
  # Punta all'immagine custom che hai costruito e pushato nel registro di OpenShift.
  # Il formato del percorso è: <registry-host>/<project-name>/<image-name>:<tag>
  # !!! MODIFICA QUESTO VALORE !!!
  image: image-registry.openshift-image-registry.svc:5000/your-project-name/custom-mirrormaker2:latest
  
  # Definisci la pipeline di mirroring
  mirrors:
  - sourceCluster: "my-source-cluster"
    targetCluster: "my-target-cluster"
    sourceConnector:
      config:
        # --- Configurazione SMT ---
        # 1. Assegna un nome alla tua catena di trasformazioni.
        transforms: "LogOnLoad"
        # 2. Specifica la classe del tuo SMT.
        transforms.LogOnLoad.type: "com.example.smt.LoggingSmT"
        # Usa la policy di replicazione di default
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
